version: '3.8'

services:
  gateway:
    volumes:
      - ./gateway:/usr/src/app
    build: ./gateway
    image: "gateway/gateway:23"
    container_name: gateway
    depends_on:
      - db
    ports:
      - 5001:5001


  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local