version: '3.3'

services:
  gateway:
    volumes:
      - ./gateway:/usr/src/app
    build: ./gateway
    image: "gateway:latest"
    container_name: gateway
    depends_on:
      - db
    ports:
      - '8080:8080'

  auth:
    volumes:
      - ./auth:/usr/src/app
    build: ./auth
    image: "auth:latest"
    container_name: auth
    depends_on:
      - db
    ports:
      - '8082:8082'


  offers:
    volumes:
      - ./offers:/usr/src/app
    build: ./offers
    image: "offers:latest"
    container_name: offers
    depends_on:
      - db
    ports:
      - '8000:8000'

  users:
    volumes:
      - ./users:/usr/src/app
    build: ./users
    image: "users:latest"
    container_name: users
    depends_on:
      - db
    ports:
      - '8081:8081'


  db:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  db:
    driver: local
